site_name: Minha Receita
repo_url: https://github.com/cuducos/minha-receita
edit_uri: edit/main/docs/
theme:
  language: pt
  name: material
  logo: favicon.svg
  favicon: favicon.svg
  palette:
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
nav:
  - index.md
  - como-usar.md
  - dicionario.md
  - instalacao.md
  - servidor.md
  - sobre-os-dados.md
  - guia-de-contribuicao.md
  - faq.md
plugins:
  - search
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
